import Head from "next/head";
import Image from "next/image";
import GlobalStyles from "../src/globalStyles";

export default function Home() {
  return (
    <div>
      <GlobalStyles />
      <Head>
        <title>eCyeshe - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>eCyeshe coming soon</h1>
      </main>
    </div>
  );
}
